#!/usr/bin/env python3
"""
post_process.py — fit generated bytes to exact target dimensions,
write a PNG + a WebP variant side-by-side, and return paths + hashes.

Strategy:
  * Load with PIL.
  * If the image needs resizing, use Lanczos.
  * If aspect ratio differs from the target, crop from the centre.
  * Preserve RGBA when transparency is present.
  * PNG (lossless) + WebP at quality 85 (good balance for web).

Output path convention (auto-detected against project root):
  1. `public/images/`  (Next.js, Remix, vanilla)
  2. `static/images/`  (Svelte, Astro)
  3. `src/assets/images/`  (Vite, Vue, CRA)
  4. creates `public/images/` if none exist
"""

from __future__ import annotations

import hashlib
import io
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Tuple

try:
    from PIL import Image
except ImportError as e:  # pragma: no cover
    print(
        "[post_process] Pillow is required — install with: pip install Pillow",
        file=sys.stderr,
    )
    raise


OUTPUT_CANDIDATES = ("public/images", "static/images", "src/assets/images")


@dataclass
class ProcessedImage:
    png_path: Path
    webp_path: Path
    sha256: str
    width: int
    height: int


def detect_output_dir(project_root: Path) -> Path:
    # Prefer an existing conventional directory
    for candidate in OUTPUT_CANDIDATES:
        p = project_root / candidate
        if p.exists():
            return p
    # Prefer public/ or static/ parent if present
    for parent_name in ("public", "static", "src/assets"):
        parent = project_root / parent_name
        if parent.exists():
            images = parent / "images"
            images.mkdir(parents=True, exist_ok=True)
            return images
    # Fallback — create public/images/
    images = project_root / "public" / "images"
    images.mkdir(parents=True, exist_ok=True)
    return images


def _resize_cover(img: Image.Image, target_w: int, target_h: int) -> Image.Image:
    """Resize + centre-crop so the image fully covers target dimensions."""
    src_w, src_h = img.size
    if (src_w, src_h) == (target_w, target_h):
        return img

    scale = max(target_w / src_w, target_h / src_h)
    new_w, new_h = int(round(src_w * scale)), int(round(src_h * scale))
    resized = img.resize((new_w, new_h), Image.LANCZOS)

    left = max(0, (new_w - target_w) // 2)
    top = max(0, (new_h - target_h) // 2)
    return resized.crop((left, top, left + target_w, top + target_h))


def _unique_path(base: Path) -> Path:
    """Append -2, -3 ... until the path is free."""
    if not base.exists():
        return base
    stem = base.stem
    suffix = base.suffix
    parent = base.parent
    i = 2
    while True:
        candidate = parent / f"{stem}-{i}{suffix}"
        if not candidate.exists():
            return candidate
        i += 1


def process(
    image_bytes: bytes,
    target_w: int,
    target_h: int,
    *,
    project_root: Path,
    filename_stem: str,
    transparent: bool,
    output_dir: Optional[Path] = None,
    overwrite: bool = False,
    webp_quality: int = 85,
) -> ProcessedImage:
    out_dir = output_dir or detect_output_dir(project_root)
    out_dir.mkdir(parents=True, exist_ok=True)

    with Image.open(io.BytesIO(image_bytes)) as img:
        if transparent:
            img = img.convert("RGBA")
        else:
            # Flatten any alpha onto white so JPEG/WebP don't carry unused alpha
            if img.mode in ("RGBA", "LA"):
                bg = Image.new("RGB", img.size, (255, 255, 255))
                bg.paste(img, mask=img.split()[-1])
                img = bg
            else:
                img = img.convert("RGB")

        final = _resize_cover(img, target_w, target_h)

        png_path = out_dir / f"{filename_stem}.png"
        webp_path = out_dir / f"{filename_stem}.webp"
        if not overwrite:
            png_path = _unique_path(png_path)
            webp_path = out_dir / f"{png_path.stem}.webp"
            webp_path = _unique_path(webp_path)

        final.save(png_path, format="PNG", optimize=True)
        final.save(webp_path, format="WEBP", quality=webp_quality, method=6)

    sha = hashlib.sha256(png_path.read_bytes()).hexdigest()
    return ProcessedImage(
        png_path=png_path,
        webp_path=webp_path,
        sha256=sha,
        width=target_w,
        height=target_h,
    )


def main() -> int:  # pragma: no cover — used only for manual smoke tests
    import argparse

    parser = argparse.ArgumentParser(description="Post-process a generated image file.")
    parser.add_argument("input", help="path to source image file (PNG/JPEG/WebP)")
    parser.add_argument("--project-root", default=".")
    parser.add_argument("--name", required=True)
    parser.add_argument("--width", type=int, required=True)
    parser.add_argument("--height", type=int, required=True)
    parser.add_argument("--transparent", action="store_true")
    parser.add_argument("--overwrite", action="store_true")
    args = parser.parse_args()

    src = Path(args.input).read_bytes()
    result = process(
        src,
        target_w=args.width,
        target_h=args.height,
        project_root=Path(args.project_root).resolve(),
        filename_stem=args.name,
        transparent=args.transparent,
        overwrite=args.overwrite,
    )
    import json
    print(json.dumps({
        "png": str(result.png_path),
        "webp": str(result.webp_path),
        "sha256": result.sha256,
        "width": result.width,
        "height": result.height,
    }, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
